stages:
# - other stages
- docker
# - deploy manifests

Build and publish docker image:
  stage: docker
  variables:
    DOCKER_HOST: tcp://localhost:2375
  services:
  - name: docker:20.10-dind
  image: docker:20.10.14
  tags:
  - shared
  - privileged
  script:
  - docker login -u v.pupkin -p s3cr3tpassw0rd registry.example.com
  - docker pull registry.example.com/bestteam/superapp:latest || true
  - docker build --cache-from registry.example.com/bestteam/superapp:latest
      --tag registry.example.com/bestteam/superapp:latest
      --tag registry.example.com/bestteam/superapp:$(cat VERSION) .
  - docker push registry.example.cat/bestteam/superapp:latest
  - docker push registry.example.cat/bestteam/superapp:$(cat VERSION)
