apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "textserver.fullname" . }}
  labels:
{{ include "textserver.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "textserver.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ .Values.config | sha256sum | quote }}
      labels:
        app.kubernetes.io/name: {{ include "textserver.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: config
            subPath: nginx.conf
      volumes:
      - name: config
        configMap:
          name: {{ include "textserver.fullname" . }}
